language: php
php:
    - 5.3.3
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --no-interaction --dev --prefer-source

script: chmod +x ./tests/run.sh && VERBOSE=true ./tests/run.sh -s ./tests/
